steps:

- name: 'gcr.io/cloud-builders/gsutil'
  id: netrc-fetch
  waitFor: ['-']
  args: ['cp', 'gs://cloud-build-antha-images/read-github-netrc.enc', '.']

- name: 'gcr.io/cloud-builders/gcloud'
  id: netrc-decrypt
  waitFor:
  - netrc-fetch
  args:
  - kms
  - decrypt
  - --ciphertext-file=read-github-netrc.enc
  - --plaintext-file=.netrc
  - --location=global
  - --keyring=continuous-deployment
  - --key=read-github

- name: 'gcr.io/cloud-builders/docker'
  id: docker-build
  waitFor:
  - netrc-decrypt
  entrypoint: '/bin/bash'
  args:
  - '-c'
  - |
    set -x -o nounset -o errexit -o pipefail
    target=tests
    if [ "$BRANCH_NAME" = "feature/future_sanity" ]; then target=cloud; fi
    docker build --force-rm -t 'eu.gcr.io/antha-images/antha-core:$COMMIT_SHA' --target=$target --build-arg COMMIT_SHA=$COMMIT_SHA --build-arg NETRC="$(cat .netrc)" .

- name: 'gcr.io/cloud-builders/docker'
  id: docker-lint
  waitFor:
  - docker-build
  entrypoint: '/bin/bash'
  args:
  - '-c'
  - |
    set -x -o nounset -o errexit -o pipefail
    docker build --force-rm --target=lint .

- name: 'gcr.io/cloud-builders/gsutil'
  id: gitlab-fetch
  waitFor: ['-']
  args: ['cp', 'gs://cloud-build-antha-images/write-gitlab-antha-root-passwd.enc', '/docker-config/.']
  volumes:
  - name: 'docker'
    path: '/docker-config'

- name: 'gcr.io/cloud-builders/gcloud'
  id: gitlab-decrypt
  waitFor:
  - gitlab-fetch
  args:
  - kms
  - decrypt
  - --ciphertext-file=/docker-config/write-gitlab-antha-root-passwd.enc
  - --plaintext-file=/docker-config/antha-root-passwd
  - --location=global
  - --keyring=continuous-deployment
  - --key=write-gitlab
  volumes:
  - name: 'docker'
    path: '/docker-config'

- name: 'gcr.io/cloud-builders/docker'
  id: docker-push
  waitFor:
  - docker-build
  - docker-lint
  - gitlab-decrypt
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    set -x -o nounset -o errexit -o pipefail
    if [ "$BRANCH_NAME" != "feature/future_sanity" ]; then exit 0; fi
    cat /docker-config/antha-root-passwd | docker login -u antha-root --password-stdin repos.antha.com:5005
    REPOS="eu.gcr.io/antha-images/antha-core:$COMMIT_SHA eu.gcr.io/antha-images/antha-core:latest repos.antha.com:5005/antha-ninja/antha-core:latest repos.antha.com:5005/antha-ninja/antha-core:$COMMIT_SHA"
    for repo in $$REPOS; do
      docker tag eu.gcr.io/antha-images/antha-core:$COMMIT_SHA $repo
      docker push $repo
    done
  volumes:
  - name: 'docker'
    path: '/docker-config'
timeout: 1000s
options:
  machineType: 'N1_HIGHCPU_8'
