package data

import (
	"github.com/apache/arrow/go/arrow/array"
)

// Series implemented on the top of Apache Arrow.
// Most of the code is autogenerated and lives in arrow.gen.go

type arrowSeriesMeta struct {
	values array.Interface
}

func (m *arrowSeriesMeta) IsBounded() bool      { return true }
func (m *arrowSeriesMeta) IsMaterialized() bool { return true }

func (m *arrowSeriesMeta) ExactSize() int {
	return m.values.Len()
}
func (m *arrowSeriesMeta) MaxSize() int {
	return m.values.Len()
}

var _ Bounded = (*arrowSeriesMeta)(nil)
